config/routes.rb
Rails.application.routes.draw do

  get 'charts/show'

  get 'charts/update'

  get 'vaccinations/create'

  get 'vaccinations/update'

  get 'vaccinations/destroy'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'home' => 'static_pages#home'
  get 'static_pages/help'
  get 'about' => 'static_pages#about'
  get 'growth_and_development' => 'static_pages#growth_and_development'
  get 'nutrition' => 'static_pages#nutrition'
  get 'vaccinations' => 'static_pages#vaccinations'
  get 'terms_of_service' => 'static_pages#terms_of_service'

  get 'signup' => 'parents#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :parents

  resources :account_activations, only: [:edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :children, only: [:create, :update, :destroy]

  resources :timelines, only: [:show, :update]

  resources :charts, only: [:show, :update]

  root 'static_pages#home'








end

app/models/parent.rb
class Parent < ActiveRecord::Base
  has_many :children, dependent: :destroy
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true

  # Returns the hash digest of the given string.
  def Parent.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def Parent.new_token
    SecureRandom.urlsafe_base64
  end

  #Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = Parent.new_token
    update_attribute(:remember_digest, Parent.digest(remember_token))
  end

  # Returns true if the given token matches the digest
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a parent.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.
  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    ParentMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes
  def create_reset_digest
    self.reset_token = Parent.new_token
    update_attribute(:reset_digest, Parent.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Send password reset email
  def send_password_reset_email
    ParentMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

    # Converts email to all lower-case
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation toekn and digest.
    def create_activation_digest
      self.activation_token = Parent.new_token
      self.activation_digest = Parent.digest(activation_token)
    end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :logged_in_parent, only: [:show, :edit, :update, :destroy]
  before_action :correct_parent, only: [:show, :edit, :update]
  before_action :correct_parent_or_admin, only: [:destroy]

  def new
    @parent = Parent.new
  end

  def show
    @parent = Parent.find(params[:id])
    if @parent.admin?
      @parents = Parent.where(admin: false).paginate(page: params[:page])
      render 'show_admin'
    else
      @child = current_parent.children.build
      @children = @parent.children
      render 'show'
    end
  end

  def create
    @parent = Parent.new(parent_params)
    if @parent.save
      @parent.send_activation_email
      flash[:info] = "Please check your email to activate your account. The message should arrive within the next 15 minutes."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @parent = Parent.find(params[:id])
  end

  def update
    @parent = Parent.find(params[:id])
    if @parent.update_attributes(parent_params)
      flash[:success] = "Profile updated"
      redirect_to @parent
    else
      render 'edit'
    end
  end

  def destroy
    if current_parent.admin?
      name = "#{Parent.find(params[:id]).first_name} #{Parent.find(params[:id]).last_name}"
      Parent.find(params[:id]).destroy
      flash[:success] = "#{name}'s account has been deleted"
      redirect_to current_parent
    else
      log_out
      Parent.find(params[:id]).destroy
      flash[:success] = "Account deleted"
      redirect_to root_url
    end
  end

  private
    def parent_params
      params.require(:parent).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

    # Confirms a logged-in parent
    def logged_in_parent
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct parent.
    def correct_parent
      @parent = Parent.find(params[:id])
      redirect_to(root_url) unless current_parent?(@parent)
    end

    # Before action for destroy
    def correct_parent_or_admin
      unless current_parent.admin?
        @parent = Parent.find(params[:id])
        redirect_to(root_url) unless current_parent?(@parent)
      end
    end

    # Confirms admin user
    def admin_user
      redirect_to(root_url) unless current_parent.admin?
    end
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/views/parents/_parent.html.erb
<tr>
  <td><%= parent.first_name %> <%= parent.last_name %></td>
  <td>Number of children: <%= parent.children.count %></td>
  <td><button type="button" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#deleteModal-<%= parent.id %>">Delete</delete></td>
  <td><%= link_to raw("<button type='button' class='btn btn-warning btn-xs'>Suspend</button>"), "#" %></td>
</tr>

<!--Modal content-->
<div id="deleteModal-<%= parent.id %>" class="modal fade" role="dialogue">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-danger">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Delete Account</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete your account? This change is irreversible.</p>
        <%= link_to raw("<button type='button' class='btn btn-danger'>Delete</button>"), parent, method: :delete %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/parents/edit.html.erb
<% provide(:title, "Settings") %>
<h1>Settings</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@parent) do |f| %>
      <%= render "shared/error_messages" %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: "form-control" %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>

      <%= f.label :password, "New Password" %>
      <%= f.text_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.text_field :password_confirmation, class: "form-control" %>

      <%= f.submit "Save changes", class: "btn btn-default" %>
    <% end %>
    <br /><br />
    <% unless current_parent.admin? %>
      <button type="button" class="btn btn-danger form-control" data-toggle="modal" data-target="#deleteModal">Delete Account</button>
    <% end %>

    <!--Modal content-->
    <div id="deleteModal" class="modal fade" role="dialogue">
  		<div class="modal-dialog">
  			<div class="modal-content">
  				<div class="modal-header bg-danger">
  					<button type="button" class="close" data-dismiss="modal">&times;</button>
  					<h4 class="modal-title">Delete Account</h4>
  				</div>
  				<div class="modal-body">
  					<p>Are you sure you want to delete your account? This change is irreversible.</p>
  					<%= link_to raw("<button type='button' class='btn btn-danger'>Delete</button>"), @parent, method: :delete %>
  				</div>
  				<div class="modal-footer">
  					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  				</div>
  			</div>
  		</div>
  	</div>

  </div>
</div>

app/views/parents/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<h3>It takes just seconds to secure your child's health</h3>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@parent) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <p><strong>By clicking "Create my account" I agree that:</strong></p>
      <ul>
        <li>I have read and accepted the <strong> <%= link_to "Terms of Service", terms_of_service_path %> </strong></li>
      </ul>
      <%= f.submit "Create my account", class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/parents/show.html.erb
<% provide(:title, "Dashboard") %>
<div class="jumbotron">
  <h1><%= @parent.first_name %>'s Dashboard</h1>
  <p class="lead">Here you will find your profile along with links to all of the individuals you have registered with Infant Passport and their at-a-glance information. </p>
  <p>
    <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#addModal">Add Newborn</button>
  </p>
</div>
<div id="page-wrapper">
  <div class="container-fluid" id="dashboard-tile">
    <%= render @children %>
  </div>
</div>
<h2>Profile</h2>
<p>Here's the information you've shared with us about yourself.</p>
<table class="table table-hover">
  <tbody>
    <tr>
      <td>Name</td>
      <td><%= @parent.first_name %> <%= @parent.last_name %></td>
    </tr>
    <tr>
      <td>Email address</td>
      <td><%= @parent.email %></td>
    </tr>
    <tr>
      <td>User Since</td>
      <td><%= @parent.created_at.strftime("%B %e, %Y") %></td>
    </tr>
  </tbody>
</table>

<!--Modal content-->
	<div id="addModal" class="modal fade" role="dialogue">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">New Infant</h4>
				</div>
				<div class="modal-body">
					<p>Enter your newborn's information here</p>
					 <%= form_for(@child) do |f| %>
            <%= render 'shared/error_messages', object:f.object %>

            <%= f.label :first_name %>
            <%= f.text_field :first_name, class: "form-control" %>

            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: "form-control" %>

            <%= f.label :date_of_birth %>
            <%= f.text_field :date_of_birth, :class => 'datepicker', :placeholder => 'mm/dd/yyyy', "data-provide" => 'datepicker', "readonly" => 'readonly' %>
            <div class="btn-group" data-toggle="buttons">
              <label class="btn btn-default">
                <%= f.radio_button :gender, false %>Male
              </label>
              <label class="btn btn-default">
                <%= f.radio_button :gender, true %>Female
              </label>
            </div>
            <br><br>
            <%= f.submit "Add child", class: "btn btn-default" %>
          <% end %>

				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>

app/views/parents/show_admin.html.erb
<% provide(:title, "Dashboard") %>
<div class="jumbotron">
  <h1><%= "#{@parent.first_name} #{@parent.last_name}" %>'s Admin Dashboard</h1>
  <p class="lead">Manage users of the Infant Passport app.</p>

</div>
<h2>Users: </h2>
<%= will_paginate %>
<table class="table table-hover">
  <tbody>
    <%= render @parents %>
  </tbody>
</table>
<%= will_paginate %>